### ISSUE TITLE
Does it work with cygwin?

### ISSUE THREAD

**Issue by derekisbusy** [faissaloo/ApertureShell#1]
I get this error when running startup in cygwin's shell...
```
Traceback (most recent call last):
  File "/usr/bin/startup", line 92, in <module>
    show_intro()
  File "/usr/bin/startup", line 56, in show_intro
    adapt_resolution()
  File "/usr/bin/startup", line 36, in adapt_resolution
    term_width=os.get_terminal_size().columns #We have check this every time
AttributeError: 'module' object has no attribute 'get_terminal_size'
```

**Comment by faissaloo** [comment]
I don't know, I've never tested this in Cygwin, only xterm and OSX's Terminal. Not sure what to do about this.

**Comment by faissaloo** [comment]
So I tested this, and I'm having no issues, are you sure the problem is with Cygwin

**Comment by derekisbusy** [comment]
I added the method from the first answer in SO and it works for me. I sent you a pull request with the change.

**Comment by faissaloo** [comment]
Ok, thank you
